apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: astyanax
  description: 'Astyanax is a high level Java client for Apache Cassandra. Apache Cassandra is a highly available column oriented database.
                Astyanax is currently in use at Netflix. Issues generally are fixed as quickly as possible and releases done frequently.'
  annotations:
    backstage.io/techdocs-ref: 'url:https://github.com/bazaarvoice/astyanax/blob/master/README.txt'
  links:
    - url: https://github.com/Netflix/astyanax/wiki
      title: Netflix - Astyanax
      icon: docs
    - url: https://github.com/Netflix/astyanax/wiki/Getting-Started
      title: Getting Started guide
      icon: docs
  tags:
    - emodb
    - java
    - astyanax
    - thrift
    - cassandra
spec:
  type: tools
  system: emodb
  lifecycle: production
  github.com/project-slug: bazaarvoice/astyanax
  owner: data-storage
